# Generated by Django 4.0 on 2021-12-30 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
