# Generated by Django 4.0 on 2022-02-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balances',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='displayed_currency',
            field=models.CharField(default='RUB', max_length=30),
        ),
    ]
