# Generated by Django 4.0 on 2022-02-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_manager', '0003_alter_balances_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currency',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
