# Generated by Django 4.0 on 2022-02-21 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_alter_operations_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operations',
            name='datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
